FROM mcr.microsoft.com/dotnet/aspnet:9.0
USER root
RUN mkdir -p /var/lib/rankoon/data-protection-keys && chown -R $APP_UID /var/lib/rankoon
USER $APP_UID
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production \
    ASPNETCORE_URLS=http://+:8080 \
    DOTNET_EnableDiagnostics=0
EXPOSE 8080
VOLUME ["/var/lib/rankoon/data-protection-keys"]

COPY artifacts/backend/ .
COPY artifacts/frontend/ ./wwwroot

ENTRYPOINT ["dotnet", "Rankoon.dll"]
