FROM mcr.microsoft.com/dotnet/aspnet:9.0
USER $APP_UID
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production \
    ASPNETCORE_URLS=http://+:8080 \
    DOTNET_EnableDiagnostics=0
EXPOSE 8080

COPY artifacts/backend/ .
COPY artifacts/frontend/ ./wwwroot

ENTRYPOINT ["dotnet", "Rankoon.dll"]
