import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TranslocoPipe, TranslocoService } from '@jsverse/transloco';
import { finalize } from 'rxjs';
import { GuildResources, GuildService } from '../../services/guild.service';
import { LevelUpAnnouncementSettings, LevelUpMessageTemplate, TemplateSchema } from '../../models/level-up-announcement.models';
import { AppStore } from '../../store/app.store';
import { ApiErrorService } from '../../services/api-error.service';
import { ToastService } from '../../services/toast.service';

@Component({ selector: 'app-level-up-announcements', standalone: true, imports: [CommonModule, FormsModule, TranslocoPipe], templateUrl: './level-up-announcements.component.html', styleUrls: ['./level-up-announcements.component.scss'] })
export class LevelUpAnnouncementsComponent implements OnInit {
  private readonly api = inject(GuildService); private readonly store = inject(AppStore); private readonly errors = inject(ApiErrorService); private readonly toast = inject(ToastService); private readonly i18n = inject(TranslocoService);
  readonly settings = signal<LevelUpAnnouncementSettings | null>(null); readonly resources = signal<GuildResources>({ roles: [], channels: [] }); readonly schema = signal<TemplateSchema | null>(null); readonly loading = signal(true); readonly saving = signal(false); readonly error = signal(''); readonly selectedId = signal<string | null>(null); readonly dirty = signal(false); readonly variationText = signal(''); readonly activeLine = signal(1); readonly activeLineLength = signal(0);
  private original = '';
  ngOnInit(): void { this.load(); }
  get selected(): LevelUpMessageTemplate | undefined { return this.settings()?.templates.find(t => t.id === this.selectedId()); }
  load(): void { const id = this.store.selectedGuild()?.id; if (!id) return; this.loading.set(true); this.api.levelUpAnnouncements(id).pipe(finalize(() => this.loading.set(false))).subscribe({ next: value => { value.settings.templates.forEach(template => { if (!template.contents?.length) template.contents = template.content ? [template.content] : ['']; }); this.settings.set(value.settings); this.original = JSON.stringify(value.settings); this.selectTemplate(value.settings.templates[0]?.id ?? null); this.api.resources(id).subscribe({ next: x => this.resources.set(x) }); this.api.levelUpTemplateSchema(id).subscribe({ next: x => this.schema.set(x) }); }, error: e => this.error.set(this.errors.resolve(e, 'errors.xpLoad').message) }); }
  changed(): void { this.dirty.set(true); }
  reset(): void { this.settings.set(JSON.parse(this.original)); this.selectTemplate(this.settings()?.templates[0]?.id ?? null); this.dirty.set(false); }
  save(): void { const id = this.store.selectedGuild(); const settings = this.settings(); if (!id || !settings) return; this.saving.set(true); this.api.saveLevelUpAnnouncements(id.id, settings).pipe(finalize(() => this.saving.set(false))).subscribe({ next: saved => { this.settings.set(saved); this.original = JSON.stringify(saved); this.dirty.set(false); this.toast.success(this.i18n.translate('levelUpAnnouncements.saved')); }, error: e => this.toast.error(this.errors.resolve(e, 'errors.save').message) }); }
  add(): void { const settings = this.settings(); if (!settings) return; const item: LevelUpMessageTemplate = { id: crypto.randomUUID().replaceAll('-', ''), name: this.i18n.translate('levelUpAnnouncements.newTemplate'), content: '', contents: ['GG {user.mention}! Level {level} ist geschafft!'], enabled: true, priority: 0, weight: 1, minimumLevel: null, maximumLevel: null, everyNthLevel: null, exactLevels: [], rewardRoleRequirement: 'Any', sources: [] }; settings.templates.push(item); this.selectTemplate(item.id); this.changed(); }
  duplicate(template: LevelUpMessageTemplate): void { const settings = this.settings(); if (!settings) return; const copy = { ...template, id: crypto.randomUUID().replaceAll('-', ''), name: `${template.name} (copy)`, contents: [...template.contents], exactLevels: [...template.exactLevels], sources: [...template.sources] }; settings.templates.push(copy); this.selectTemplate(copy.id); this.changed(); }
  remove(template: LevelUpMessageTemplate): void { const settings = this.settings(); if (!settings) return; settings.templates = settings.templates.filter(t => t.id !== template.id); this.selectTemplate(settings.templates[0]?.id ?? null); this.changed(); }
  selectTemplate(id: string | null): void { this.selectedId.set(id); const template = this.settings()?.templates.find(item => item.id === id); const value = template?.contents.join('\n') ?? ''; this.variationText.set(value); this.activeLine.set(1); this.activeLineLength.set(value.split(/\r?\n/)[0]?.length ?? 0); }
  updateVariations(value: string, input?: HTMLTextAreaElement): void { const template = this.selected; if (!template) return; const limited = value.split(/\r?\n/).map(line => line.slice(0, 500)).join('\n'); if (input && input.value !== limited) input.value = limited; this.variationText.set(limited); template.contents = limited.split(/\r?\n/).filter(line => line.trim().length > 0); if (input) this.updateActiveLineCount(input); this.changed(); }
  updateActiveLineCount(input: HTMLTextAreaElement): void { const cursor = input.selectionStart ?? 0; const before = input.value.slice(0, cursor); const line = before.split(/\r?\n/).length; const lineStart = Math.max(before.lastIndexOf('\n'), before.lastIndexOf('\r')) + 1; this.activeLine.set(line); this.activeLineLength.set(before.length - lineStart); }
  insertToken(token: string, input: HTMLTextAreaElement): void { const value = this.variationText(); const start = input.selectionStart ?? value.length; const updated = value.slice(0, start) + `{${token}}` + value.slice(input.selectionEnd ?? start); this.updateVariations(updated, input); setTimeout(() => { input.focus(); input.selectionStart = input.selectionEnd = Math.min(start + token.length + 2, input.value.length); this.updateActiveLineCount(input); }); }
  test(): void { const id = this.store.selectedGuild()?.id; const template = this.selected; if (!id || !template) return; this.api.testLevelUpAnnouncement(id, this.request(template)).subscribe({ next: () => this.toast.success(this.i18n.translate('levelUpAnnouncements.testSent')), error: e => this.toast.error(this.errors.resolve(e, 'errors.save').message) }); }
  textChannels = () => this.resources().channels.filter(c => c.type.includes('Text'));
  variationLineNumbers(): number[] { return Array.from({ length: Math.max(1, this.variationText().split(/\r?\n/).length) }, (_, index) => index + 1); }
  private request(template: LevelUpMessageTemplate) { return { template, level: 23, previousLevel: 22, totalXp: 12000, gainedXp: 50, source: 'message', rewardRoleAwarded: template.rewardRoleRequirement === 'Required' }; }
}
