import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppStore } from '../../store/app.store';
import { GuildResources, GuildService, VcHub } from '../../services/guild.service';

@Component({ selector: 'app-vc-hubs', standalone: true, imports: [CommonModule, FormsModule], styleUrls: ['./vc-hubs.component.scss'], template: `
<section class="page"><header><div><p class="eyebrow">JOIN TO CREATE</p><h1>VC-Hubs</h1><p>Beim Betreten eines Hub-Kanals erzeugt Rankoon einen privaten, aufraeumbaren Voice-Kanal.</p></div><button (click)="newHub()">+ Hub anlegen</button></header>
<p class="notice" *ngIf="message()">{{ message() }}</p><div class="grid"><article class="hub" *ngFor="let hub of hubs()"><div class="hub-title"><h2>{{ hub.nameTemplate }}</h2><label><input type="checkbox" [(ngModel)]="hub.enabled"> Aktiv</label></div><div class="fields"><label>Vorhandener Hub-Kanal<select [(ngModel)]="hub.joinChannelId"><option [ngValue]="0">Vom Bot erstellen</option><option *ngFor="let channel of voiceChannels()" [ngValue]="channel.id">{{ channel.name }}</option></select></label><label *ngIf="!hub.joinChannelId">Neuer Hub-Name<input [(ngModel)]="hub.hubChannelName" placeholder="VC erstellen"></label><label>Zielkategorie<select [(ngModel)]="hub.categoryId"><option [ngValue]="null">Keine Kategorie</option><option *ngFor="let channel of categories()" [ngValue]="channel.id">{{ channel.name }}</option></select></label><label>Name<input [(ngModel)]="hub.nameTemplate" placeholder="{username}s Kanal"></label><label>Limit<input type="number" [(ngModel)]="hub.userLimit"></label><label>Bitrate<input type="number" [(ngModel)]="hub.bitrate"></label><label>Max. Kanaele / Owner<input type="number" min="1" [(ngModel)]="hub.maxChannelsPerOwner"></label></div><footer><span>Owner nutzt: /voice name, /voice limit, /voice lock, /voice unlock, /voice kick und /voice transfer</span><button (click)="save(hub)">Speichern</button><button class="danger" *ngIf="hub.id" (click)="remove(hub)">Loeschen</button></footer></article></div></section>` })
export class VcHubsComponent implements OnInit {
  readonly appStore = inject(AppStore); private readonly api = inject(GuildService); readonly hubs = signal<VcHub[]>([]); readonly resources = signal<GuildResources | null>(null); readonly message = signal('');
  voiceChannels = () => this.resources()?.channels.filter(x => x.type.includes('Voice')) ?? []; categories = () => this.resources()?.channels.filter(x => x.type.includes('Category')) ?? [];
  ngOnInit(): void { const id = this.appStore.selectedGuild()?.id; if (!id) return; this.api.hubs(id).subscribe(h => this.hubs.set(h)); this.api.resources(id).subscribe(r => this.resources.set(r)); }
  newHub(): void { this.hubs.update(items => [...items, { joinChannelId: 0, hubChannelName: 'VC erstellen', categoryId: null, nameTemplate: '{username}s Kanal', userLimit: 0, bitrate: 64000, maxChannelsPerOwner: 1, enabled: true }]); }
  save(hub: VcHub): void { const id = this.appStore.selectedGuild()?.id; if (!id) return; const request = hub.id ? this.api.updateHub(id, hub) : this.api.createHub(id, hub); request.subscribe({ next: saved => { this.hubs.update(items => items.map(x => x === hub ? saved : x)); this.message.set('VC-Hub gespeichert.'); }, error: () => this.message.set('Speichern fehlgeschlagen.') }); }
  remove(hub: VcHub): void { const id = this.appStore.selectedGuild()?.id; if (!id || !hub.id) return; this.api.deleteHub(id, hub.id).subscribe(() => this.hubs.update(items => items.filter(x => x.id !== hub.id))); }
}
