import { CommonModule } from '@angular/common';
import { Component, computed, input, output } from '@angular/core';
import { TranslocoPipe } from '@jsverse/transloco';
import { BotManagementRange, OperationsInsight, OperationsMetric, OperationsTrendPoint } from './bot-management.models';

@Component({ selector: 'app-operations-report', standalone: true, imports: [CommonModule, TranslocoPipe], template: `
  <section class="report">
    <header class="rk-page-header"><div><h2>{{ ('botManagement.sections.' + page() + '.title') | transloco }}</h2><p class="rk-page-header__description">{{ ('botManagement.sections.' + page() + '.description') | transloco }}</p></div><div class="range" role="group" [attr.aria-label]="'botManagement.range' | transloco">@for (option of ranges; track option) { <button type="button" [class.active]="range() === option" [attr.aria-pressed]="range() === option" (click)="rangeChange.emit(option)">{{ ('botManagement.ranges.' + option) | transloco }}</button> }</div></header>
    @if (loading() && !metrics().length) { <div class="rk-panel state" role="status">{{ 'common.loading' | transloco }}</div> }
    @if (error()) { <div class="rk-notice rk-notice--danger" role="alert">{{ error() }} <button class="rk-button" type="button" (click)="retry.emit()">{{ 'common.retry' | transloco }}</button></div> }
    @if (!loading() && !error() && !metrics().length && !trend().length && !insights().length) { <div class="rk-panel state"><div class="mascot-slot" aria-hidden="true"></div><h3>{{ 'botManagement.empty.title' | transloco }}</h3><p>{{ 'botManagement.empty.description' | transloco }}</p></div> }
    @if (metrics().length) { <div class="metrics">@for (metric of visibleMetrics(); track metric.code) { <article class="rk-panel"><span>{{ ('botManagement.domain.metrics.' + metric.code) | transloco }}</span><strong>{{ metric.value | number }}</strong><small>{{ metric.changePercent === null ? ('botManagement.noComparison' | transloco) : (metric.changePercent | number:'1.0-1') + '%' }}</small></article> }</div> }
    @if (trend().length) { <article class="rk-panel"><h3>{{ 'botManagement.trend' | transloco }}</h3><ul class="trend" [attr.aria-label]="'botManagement.trendFallback' | transloco">@for (point of trend(); track point.timestamp) { <li><time>{{ point.timestamp | date:'medium' }}</time><strong>{{ point.value | number }}</strong><span>{{ 'botManagement.previous' | transloco }} {{ point.previousValue === null ? '-' : (point.previousValue | number) }}</span></li> }</ul></article> }
    @if (insights().length) { <article class="rk-panel"><h3>{{ 'botManagement.insights' | transloco }}</h3><ul class="insights">@for (item of insights(); track item.code) { <li [class]="item.severity"><strong>{{ ('botManagement.domain.insights.' + item.code) | transloco }}</strong><code>{{ item.code }}</code></li> }</ul></article> }
  </section>
`, styles: [`
  .report { display: grid; gap: var(--rk-space-5); }.range { display: flex; gap: var(--rk-space-1); padding: var(--rk-space-1); background: var(--rk-surface-1); border: 1px solid var(--rk-border-subtle); border-radius: var(--rk-radius-md); }.range button { min-height: var(--rk-control-height); padding: 0 var(--rk-space-3); color: var(--rk-text-muted); background: transparent; border: 1px solid transparent; border-radius: var(--rk-radius-sm); }.range button:hover { background: var(--rk-surface-2); }.range button.active { color: var(--rk-text-strong); background: var(--rk-brand-subtle); border-color: var(--rk-brand); }.metrics { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: var(--rk-space-3); }.metrics article { display: grid; gap: var(--rk-space-2); }.metrics span, small, .trend span, time { color: var(--rk-text-muted); }.metrics strong { color: var(--rk-text-strong); font-size: 1.65rem; }.trend, .insights { display: grid; gap: var(--rk-space-2); padding: 0; list-style: none; }.trend li { display: grid; grid-template-columns: 1fr auto auto; gap: var(--rk-space-3); padding: var(--rk-space-3); background: var(--rk-surface-2); border-radius: var(--rk-radius-md); }.insights li { display: flex; justify-content: space-between; gap: var(--rk-space-3); padding: var(--rk-space-3); border-left: var(--rk-space-1) solid var(--rk-info); background: var(--rk-surface-2); border-radius: var(--rk-radius-md); }.insights .warning { border-color: var(--rk-warning); }.insights .critical { border-color: var(--rk-danger); }.insights .success { border-color: var(--rk-success); }.insights code { color: var(--rk-text-muted); }.state { min-height: calc(var(--rk-control-height) * 4); display: grid; place-content: center; gap: var(--rk-space-3); text-align: center; }
  @media (max-width: 900px) { .metrics { grid-template-columns: repeat(2, 1fr); } } @media (max-width: 768px) { .range { width: 100%; }.range button { flex: 1; }.trend li { grid-template-columns: 1fr auto; }.trend li span { grid-column: 1 / -1; } } @media (max-width: 480px) { .metrics { grid-template-columns: 1fr; } }
`] })
export class OperationsReportComponent {
  readonly page = input.required<string>(); readonly range = input.required<BotManagementRange>(); readonly metrics = input<OperationsMetric[]>([]); readonly trend = input<OperationsTrendPoint[]>([]); readonly insights = input<OperationsInsight[]>([]); readonly loading = input(false); readonly error = input<string | null>(null); readonly rangeChange = output<BotManagementRange>(); readonly retry = output<void>();
  readonly ranges: BotManagementRange[] = ['24h', '7d', '30d', '90d']; readonly visibleMetrics = computed(() => this.metrics().slice(0, 4));
}
